### ISSUE TITLE
WorldGuard flag to allow crafts?

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-WorldGuard#6]
I have a section in my spawn I wish for players to be able to use a demo craft in, I also have areas in the world they can buy crafts, but if I enable this plugn it blocks all use. Can we please have a flag that allows setting using crafts in WG regions without build.

**Comment by TylerS1066** [comment]
This has been on our wish list since the start of this plugin (as evidenced by the language entries for custom flags).

I've started working on implementing the feature on the [`custom-flags` branch](https://github.com/APDevTeam/Movecraft-WorldGuard/tree/custom-flags).  The dev builds aren't ready yet, but I'll update you once they are.


The main part is that we will be adding the following WorldGuard state flags (ALLOW/DENY/NONE):
- allow-combat-release
- allow-craft-pilot
- allow-craft-rotate
- allow-craft-sink
- allow-craft-translate

These flags will override the current PVP/TNT/BUILD flag behavior.

**Comment by TomLewis** [comment]
Superb, glad it's being worked on. Thanks.

**Comment by TylerS1066** [comment]
As of the merging of #7, this feature is added!

You can get a dev build from the GitHub Actions CI [here](https://github.com/APDevTeam/Movecraft-WorldGuard/actions/runs/1770040401).

The wiki has a new page [here](https://github.com/APDevTeam/Movecraft-WorldGuard/wiki/Custom-Flags) which describes the interaction of the new custom flags and the old flags.

**Comment by TomLewis** [comment]
Woohoo! and docs!
